name: Deploy HTML app to Azure Web App - technology-services

on:
  push:
    branches:
      - main  # This workflow triggers on push to the main branch.
  workflow_dispatch:  # This also allows for manual workflow runs.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'technology-services' # Your actual Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

